In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

# LabelEncoder 객체 생성
encoder = LabelEncoder()

# 1. 데이터 로딩
file_path = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/titanic.csv"
df = pd.read_csv(file_path)

# 2. 결측치 확인
print(df.isnull().sum())
print("================================================================")

# 3. 결측치 제거 (Age의 결측치는 평균나이로)
df['Age'].fillna(df['Age'].mean(), inplace=True)
df.dropna(inplace=True)
print(df)
print("================================================================")

# 4. 레이블 확인(생존자 확인)
print(df['Survived'].value_counts())
print("================================================================")

# 5. 불필요한 컬럼 제거
df.drop(["Name", "Ticket", "Embarked"], axis=1, inplace=True)
print(df)
print("================================================================")

# 6. 인코딩(머신러닝과 딥러닝의 모든 값을 숫자로 변경, 단 머신러닝의 label은 제외)
for column in df.select_dtypes(include=['object']).columns:
    df[column] = encoder.fit_transform(df[column])
print(df)
print("================================================================")

# 특징과 결과값 지정
X = df.drop('Survived', axis=1)
Y = df["Survived"]

# 훈련 데이터와 테스트 데이터 분리 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# 모델 정의
models = {
    'Linear Regression': LinearRegression(),
    'Support Vector Machine': SVR(),
    'Random Forest': RandomForestRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'K-Nearest Neighbors': KNeighborsRegressor()
}

for model_name, model in models.items():
    model.fit(X_train, y_train)  # 훈련
    y_pred = model.predict(X_test)  # 예측
    
    # 연속적인 예측값을 0 또는 1로 변환해야 정확도와 혼동 행렬 확인 가능
    y_pred_binary = np.where(y_pred > 0.5, 1, 0)


    print(f"{model_name} 모델")
    print("정확도(Accuracy):", accuracy_score(y_test, y_pred_binary))
    print("혼동 행렬(Confusion Matrix):\n", confusion_matrix(y_test, y_pred_binary))
    print("="*50)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
================================================================
     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
6              7         0       1
10            11         1       3
11            12         1       1
..           ...       ...     ...
871          872         1       1
872          873         0       1
879          880         1       1
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
872                           Carlsson, Mr. Frans Olof    male  33.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch    Ticket     Fare        Cabin Embarked
1        0  PC 17599  71.2833          C85        C
3        0    113803  53.1000         C123        S
6        0     17463  51.8625          E46        S
10       1   PP 9549  16.7000           G6        S
11       0    113783  26.5500         C103        S
..     ...       ...      ...          ...      ...
871      1     11751  52.5542          D35        S
872      0       695   5.0000  B51 B53 B55        S
879      1     11767  83.1583          C50        C
887      0    112053  30.0000          B42        S
889      0    111369  30.0000         C148        C

[202 rows x 12 columns]
================================================================
1    134
0     68
Name: Survived, dtype: int64
================================================================
     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
1              2         1       1  female  38.0      1      0  71.2833
3              4         1       1  female  35.0      1      0  53.1000
6              7         0       1    male  54.0      0      0  51.8625
10            11         1       3  female   4.0      1      1  16.7000
11            12         1       1  female  58.0      0      0  26.5500
..           ...       ...     ...     ...   ...    ...    ...      ...
871          872         1       1  female  47.0      1      1  52.5542
872          873         0       1    male  33.0      0      0   5.0000
879          880         1       1  female  56.0      0      1  83.1583
887          888         1       1  female  19.0      0      0  30.0000
889          890         1       1    male  26.0      0      0  30.0000

           Cabin
1            C85
3           C123
6            E46
10            G6
11          C103
..           ...
871          D35
872  B51 B53 B55
879          C50
887          B42
889         C148

[202 rows x 9 columns]
================================================================
     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin
1              2         1       1    0  38.0      1      0  71.2833     80
3              4         1       1    0  35.0      1      0  53.1000     54
6              7         0       1    1  54.0      0      0  51.8625    128
10            11         1       3    0   4.0      1      1  16.7000    144
11            12         1       1    0  58.0      0      0  26.5500     48
..           ...       ...     ...  ...   ...    ...    ...      ...    ...
871          872         1       1    0  47.0      1      1  52.5542    101
872          873         0       1    1  33.0      0      0   5.0000     33
879          880         1       1    0  56.0      0      1  83.1583     69
887          888         1       1    0  19.0      0      0  30.0000     29
889          890         1       1    1  26.0      0      0  30.0000     59

[202 rows x 9 columns]
================================================================
Linear Regression 모델
정확도(Accuracy): 0.8536585365853658
혼동 행렬(Confusion Matrix):
 [[ 7  1]
 [ 5 28]]
==================================================
Support Vector Machine 모델
정확도(Accuracy): 0.8048780487804879
혼동 행렬(Confusion Matrix):
 [[ 0  8]
 [ 0 33]]
==================================================
Random Forest 모델
정확도(Accuracy): 0.7560975609756098
혼동 행렬(Confusion Matrix):
 [[ 4  4]
 [ 6 27]]
==================================================
Decision Tree 모델
정확도(Accuracy): 0.8048780487804879
혼동 행렬(Confusion Matrix):
 [[ 6  2]
 [ 6 27]]
==================================================
K-Nearest Neighbors 모델
정확도(Accuracy): 0.6829268292682927
혼동 행렬(Confusion Matrix):
 [[ 3  5]
 [ 8 25]]
==================================================